import { Navigation } from "@/components/navigation"
import { Footer } from "@/components/footer"
import { ComparisonTable } from "@/components/comparison-table"

// Mock data - in real app this would come from database
const vpnProducts = [
  {
    id: 1,
    name: "ExpressVPN",
    logo: "/expressvpn-logo.png",
    rating: 4.8,
    reviewCount: 12500,
    price: "$8.32/month",
    priceNote: "15-month plan",
    badge: "Editor's Choice",
    badgeColor: "bg-blue-600 text-white",
    features: {
      servers: "3000+",
      countries: 94,
      noLogs: true,
      killSwitch: true,
      speed: "Ultra Fast",
      streaming: true,
      torrenting: true,
      support: "24/7 Live Chat",
      devices: 5,
      moneyBack: 30,
    },
    affiliateUrl: "https://expressvpn.com/?a=globalcompare",
    ctaText: "Get ExpressVPN",
    discountText: "Save 49%",
    pros: [
      "Fastest speeds in our tests",
      "Works with all streaming services",
      "Excellent customer support",
      "Strong privacy policy",
    ],
    cons: ["More expensive than competitors", "Limited simultaneous connections"],
    description: "Premium VPN service with the fastest speeds and best streaming support.",
  },
  {
    id: 2,
    name: "NordVPN",
    logo: "/nordvpn-logo.jpg",
    rating: 4.7,
    reviewCount: 18900,
    price: "$3.99/month",
    priceNote: "2-year plan",
    badge: "Best Value",
    badgeColor: "bg-green-600 text-white",
    features: {
      servers: "5400+",
      countries: 60,
      noLogs: true,
      killSwitch: true,
      speed: "Very Fast",
      streaming: true,
      torrenting: true,
      support: "24/7 Live Chat",
      devices: 6,
      moneyBack: 30,
    },
    affiliateUrl: "https://nordvpn.com/?a=globalcompare",
    ctaText: "Get NordVPN",
    discountText: "Save 68%",
    pros: ["Great value for money", "Large server network", "Advanced security features", "User-friendly apps"],
    cons: ["Inconsistent speeds", "Some servers are slow"],
    description: "Feature-rich VPN with excellent value and strong security features.",
  },
  {
    id: 3,
    name: "Surfshark",
    logo: "/surfshark-logo.jpg",
    rating: 4.5,
    reviewCount: 8700,
    price: "$2.49/month",
    priceNote: "2-year plan",
    badge: "Unlimited Devices",
    badgeColor: "bg-purple-600 text-white",
    features: {
      servers: "3200+",
      countries: 65,
      noLogs: true,
      killSwitch: true,
      speed: "Fast",
      streaming: true,
      torrenting: true,
      support: "24/7 Live Chat",
      devices: "Unlimited",
      moneyBack: 30,
    },
    affiliateUrl: "https://surfshark.com/?a=globalcompare",
    ctaText: "Get Surfshark",
    discountText: "Save 82%",
    pros: [
      "Unlimited simultaneous connections",
      "Very affordable pricing",
      "Good streaming performance",
      "Clean and simple interface",
    ],
    cons: ["Newer company with less track record", "Speeds can vary"],
    description: "Budget-friendly VPN with unlimited device connections and solid performance.",
  },
  {
    id: 4,
    name: "CyberGhost",
    logo: "/placeholder-logo.png",
    rating: 4.4,
    reviewCount: 6800,
    price: "$2.19/month",
    priceNote: "3-year plan",
    badge: "Best for Beginners",
    badgeColor: "bg-orange-600 text-white",
    features: {
      servers: "7000+",
      countries: 91,
      noLogs: true,
      killSwitch: true,
      speed: "Fast",
      streaming: true,
      torrenting: true,
      support: "24/7 Live Chat",
      devices: 7,
      moneyBack: 45,
    },
    affiliateUrl: "https://cyberghost.com/?a=globalcompare",
    ctaText: "Get CyberGhost",
    discountText: "Save 84%",
    pros: [
      "User-friendly interface",
      "Large server network",
      "45-day money-back guarantee",
      "Specialized streaming servers",
    ],
    cons: ["Slower speeds on distant servers", "Limited advanced features"],
    description: "Beginner-friendly VPN with extensive server network and long money-back guarantee.",
  },
  {
    id: 5,
    name: "Private Internet Access",
    logo: "/placeholder-logo.png",
    rating: 4.3,
    reviewCount: 5200,
    price: "$2.03/month",
    priceNote: "3-year plan",
    badge: "Most Servers",
    badgeColor: "bg-red-600 text-white",
    features: {
      servers: "35000+",
      countries: 84,
      noLogs: true,
      killSwitch: true,
      speed: "Fast",
      streaming: true,
      torrenting: true,
      support: "24/7 Live Chat",
      devices: 10,
      moneyBack: 30,
    },
    affiliateUrl: "https://privateinternetaccess.com/?a=globalcompare",
    ctaText: "Get PIA",
    discountText: "Save 83%",
    pros: [
      "Largest server network",
      "Open-source applications",
      "Proven no-logs policy",
      "Advanced customization options",
    ],
    cons: ["Complex interface for beginners", "Inconsistent streaming performance"],
    description: "Technical VPN with the largest server network and proven privacy track record.",
  },
  {
    id: 6,
    name: "IPVanish",
    logo: "/placeholder-logo.png",
    rating: 4.2,
    reviewCount: 4100,
    price: "$3.33/month",
    priceNote: "2-year plan",
    badge: "Self-Owned Network",
    badgeColor: "bg-indigo-600 text-white",
    features: {
      servers: "2000+",
      countries: 75,
      noLogs: true,
      killSwitch: true,
      speed: "Very Fast",
      streaming: true,
      torrenting: true,
      support: "24/7 Live Chat",
      devices: "Unlimited",
      moneyBack: 30,
    },
    affiliateUrl: "https://ipvanish.com/?a=globalcompare",
    ctaText: "Get IPVanish",
    discountText: "Save 77%",
    pros: [
      "Owns and operates all servers",
      "Unlimited simultaneous connections",
      "Fast connection speeds",
      "SOCKS5 proxy included",
    ],
    cons: ["Based in US (Five Eyes)", "Limited streaming server options"],
    description: "US-based VPN provider with self-owned server infrastructure and unlimited connections.",
  },
]

const vpnFeatures = [
  { key: "servers", name: "Servers", type: "text" as const, important: true },
  { key: "countries", name: "Countries", type: "text" as const, important: true },
  { key: "noLogs", name: "No-Logs Policy", type: "boolean" as const, important: true },
  { key: "killSwitch", name: "Kill Switch", type: "boolean" as const, important: true },
  { key: "speed", name: "Speed", type: "text" as const, important: true },
  { key: "streaming", name: "Streaming", type: "boolean" as const, important: true },
  { key: "torrenting", name: "P2P/Torrenting", type: "boolean" as const, important: false },
  { key: "support", name: "Customer Support", type: "text" as const, important: false },
  { key: "devices", name: "Simultaneous Devices", type: "text" as const, important: true },
  { key: "moneyBack", name: "Money-Back Guarantee", type: "text" as const, important: false },
]

export default function VPNPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navigation />
      <main className="flex-1 container mx-auto px-4 py-8">
        <ComparisonTable
          products={vpnProducts}
          features={vpnFeatures}
          category="VPN"
          title="Best VPN Services 2025"
          description="Compare the top VPN providers by speed, security, and features. Our experts have tested over 50 VPN services to bring you the most comprehensive comparison for 2025."
        />
      </main>
      <Footer />
    </div>
  )
}
